name: Changelog updated

on:
  push:
    branches: [ "*" ]
    paths:
      - CHANGELOG.md

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Simple Diff
        uses: mudlabs/simple-diff@v1.2.0
        id: diff
      - run: exit 1
        if: steps.diff.outputs.modified == false